class AminaCasino{
constructor(){
this.b={HC:this.getHC(),AMINA:0};this.c='HC';this.w=this.getW();this.t=this.getT();this.p=null;this.aid=1107424865;this.cw='UX3PHCY7QNGOHXWNWTZIXK5T3MBDZKYCFN7PAVCT2H4G4JEZKJK6W7UG44';this.cc=0;this.dp=!1;this.ds=0;this.sq=[];this.ls=0;this.g={s:{syms:['⭐','🌟','💫','🌌','🪐','🌙','☄️','🚀','👽','🛸'],sct:'🌠',grid:[],spin:0,win:0,mult:1,spins:0,state:null},p:{balls:[],max:5},bj:{pH:[],dH:[],deck:[],act:0,bet:0,dbl:0,spl:0,ins:0,spH:[],cDbl:0,cSpl:0},h:{card:null,strk:0,bet:0,act:0},d:{bet:null,v1:1,v2:1,roll:0,hot:[]}};this.m={on:0,aud:null};this.hap=navigator.vibrate||navigator.webkitVibrate;this.atomicRestore();this.initP();this.init();this.check();}
vib(p=50){if(this.hap&&'ontouchstart'in window)try{this.hap.call(navigator,p)}catch(e){}}
load(el,tx='Loading...'){if(!el)return;el.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><div style="width:16px;height:16px;border:2px solid #fff3;border-top:2px solid #FFD700;border-radius:50%;animation:rotate 1s linear infinite"></div>${tx}</div>`;el.disabled=1}
unload(el,tx){if(!el)return;el.innerHTML=tx;el.disabled=0}
anim(){const b=$('balanceAmount');if(b){b.classList.add('updating');setTimeout(()=>b.classList.remove('updating'),300)}}
getHC(){const d=new Date().toDateString(),s=localStorage.getItem('hc_data');if(s){const dt=JSON.parse(s);if(dt.date===d)return dt.balance}localStorage.setItem('hc_data',JSON.stringify({date:d,balance:1000}));return 1000}
saveHC(){localStorage.setItem('hc_data',JSON.stringify({date:new Date().toDateString(),balance:this.b.HC}))}
getT(){return localStorage.getItem('session_token')||null}
saveT(t){localStorage.setItem('session_token',t);this.t=t}
clearT(){localStorage.removeItem('session_token');this.t=null}
getW(){const s=localStorage.getItem('connected_wallet')||sessionStorage.getItem('connected_wallet');return s?JSON.parse(s):null}
saveW(){['localStorage','sessionStorage'].forEach(s=>window[s].setItem('connected_wallet',JSON.stringify(this.w)));if(this.b.AMINA>0)['localStorage','sessionStorage'].forEach(s=>window[s].setItem('cached_amina_balance',this.b.AMINA.toString()));this.saveApp()}
clearW(){['connected_wallet','cached_amina_balance','app_state'].forEach(k=>['localStorage','sessionStorage'].forEach(s=>window[s].removeItem(k)))}
saveApp(){const st={inCasino:!$('welcomeScreen').classList.contains('active'),currency:this.c,timestamp:Date.now()};['localStorage','sessionStorage'].forEach(s=>window[s].setItem('app_state',JSON.stringify(st)))}
saveGameState(){localStorage.setItem('game_state',JSON.stringify({slots:this.g.s.state,hilo:this.g.h.act?this.g.h:null,timestamp:Date.now()}))}
loadGameState(){const gs=localStorage.getItem('game_state');if(gs){const state=JSON.parse(gs);if(Date.now()-state.timestamp<3e5){if(state.slots&&this.g.s.spins>0)this.g.s.state=state.slots;if(state.hilo&&state.hilo.act)this.g.h=state.hilo}}}
atomicRestore(){const ch=localStorage.getItem('cached_amina_balance')||sessionStorage.getItem('cached_amina_balance');if(ch&&this.w)this.b.AMINA=parseFloat(ch);if(this.w){this.forceAMINA()}else{this.forceHC()}}
async check(){try{if(this.dp)return;if(this.w){this.forceAMINA();this.updWal();this.loadGameState();this.sync();setTimeout(()=>this.refWal(),500);this.processSyncQueue()}}catch(e){console.log('Check error:',e);this.forceHC()}}
updCur(){const tg=$('currencyToggle'),tx=tg?.querySelector('.currency-text');if(this.c==='AMINA'){tg?.classList.add('amina');if(tx)tx.textContent='AMINA'}else{tg?.classList.remove('amina');if(tx)tx.textContent='HC'}}
async refWal(){if(!this.w)return;try{const bal=await this.fetchAmina(this.w);this.b.AMINA=bal;['localStorage','sessionStorage'].forEach(s=>window[s].setItem('cached_amina_balance',bal.toString()));this.updCash();this.anim()}catch(e){}}
async refSess(){if(!this.w)return!1;try{this.clearT();const res=await this.callSess('create_session',{wallet:this.w});if(res.success){this.saveT(res.token);this.cc=res.balance||0;this.updDisp();this.updCash();return!0}}catch(e){}return!1}
async callSess(act,data){try{const res=await fetch('/.netlify/functions/session-manager',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:act,...data})});return await res.json()}catch(e){return{success:!1,error:e.message}}}
async sync(){if(this.dp||(!this.w&&!this.t))return;try{const body=this.t?{action:'get_balance',token:this.t}:{action:'get_balance',wallet:this.w},res=await fetch('/.netlify/functions/casino-credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await res.json();if(result.success){this.cc=result.balance||0;if(result.token&&!this.t)this.saveT(result.token);this.updDisp();this.updCash();this.ls=Date.now()}else if(result.needsRefresh&&this.w)await this.refSess()}catch(e){if(this.w&&!this.t&&!this.dp)await this.refSess()}}
async updServ(act,amt){if(!this.t)return!1;const req={action:act,token:this.t,amount:amt,timestamp:Date.now()};try{const res=await fetch('/.netlify/functions/casino-credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)}),result=await res.json();if(result.success){this.cc=result.newBalance||result.balance||0;this.updDisp();this.updCash();this.ls=Date.now();return!0}else{this.sq.push(req);return!1}}catch(e){this.sq.push(req);return!1}}
async processSyncQueue(){if(this.sq.length===0||!this.t)return;const req=this.sq.shift();try{const res=await fetch('/.netlify/functions/casino-credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)}),result=await res.json();if(result.success){this.cc=result.newBalance||result.balance||0;this.updDisp();this.updCash();this.ls=Date.now();if(this.sq.length>0)setTimeout(()=>this.processSyncQueue(),100)}else this.sq.unshift(req)}catch(e){this.sq.unshift(req)}setTimeout(()=>this.processSyncQueue(),5e3)}
async fetchAmina(wal){try{const res=await fetch(`https://mainnet-idx.algonode.cloud/v2/accounts/${wal}/assets`),data=await res.json(),asset=data.assets?.find(a=>a['asset-id']===this.aid),bal=asset?asset.amount/1e8:0;['localStorage','sessionStorage'].forEach(s=>window[s].setItem('cached_amina_balance',bal.toString()));return bal}catch(e){this.notify('❌ Error fetching balance');const ch=localStorage.getItem('cached_amina_balance')||sessionStorage.getItem('cached_amina_balance');return ch?parseFloat(ch):0}}
initP(){try{if(typeof PeraWalletConnect!=='undefined'){this.p=new PeraWalletConnect({shouldShowSignTxnToast:!1,chainId:416001});if(typeof this.p.connect==='function'&&typeof this.p.signTransaction==='function')this.p.connector?.on('disconnect',()=>{this.handleWalletDisconnect()});else this.p=null}else this.p=null}catch(e){this.p=null}}
handleWalletDisconnect(){this.w=null;this.b.AMINA=0;this.clearW();this.clearT();if(this.g.h.act)this.autoCashHilo();this.forceHC();this.updWal();this.notify('🔓 Wallet disconnected - switched to HC mode')}
init(){this.setupUI();this.setupGames();this.setupMusic();this.createFX();this.updDisp()}
setupUI(){$('enterCasino').onclick=()=>{this.vib(50);this.enter()};$('walletBtn').onclick=()=>{this.vib(75);this.togWal()};$('currencyToggle').onclick=()=>{this.vib(25);this.togCur()};this.setupOrb();$$('.game-card').forEach(c=>c.onclick=()=>{this.vib(50);this.switch(c.dataset.game)})}
setupOrb(){const orb=$('cosmicOrb'),menu=$('orbitalMenu');let open=0;orb.onclick=()=>{this.vib(75);open=!open;menu.classList.toggle('open',open);orb.style.transform=open?'scale(0.9)':'scale(1)'};$$('.orbital-item').forEach(i=>i.onclick=()=>{this.vib(50);this.switch(i.dataset.game);open=0;menu.classList.remove('open');orb.style.transform='scale(1)'});document.addEventListener('click',e=>{if(!e.target.closest('.cosmic-orb-menu')&&open){open=0;menu.classList.remove('open');orb.style.transform='scale(1)'}})}
enter(){const btn=$('enterCasino');this.load(btn,'Entering...');setTimeout(()=>{$('welcomeScreen').classList.remove('active');$('mainCasino').classList.add('active');this.saveApp();if(this.w){this.fetchAmina(this.w).then(bal=>{this.b.AMINA=bal;this.updCash()});this.sync()}if(this.m.aud&&!this.m.on)this.m.aud.play().then(()=>{this.m.on=1;$('musicToggle').innerHTML='🎵'}).catch(()=>{});this.unload(btn,'🚀 ENTER CASINO')},800)}
async togWal(){if(this.w){try{if(this.p&&typeof this.p.disconnect==='function')await this.p.disconnect();else this.handleWalletDisconnect()}catch(e){this.handleWalletDisconnect()}this.notify('🔓 Wallet disconnected');this.vib(100)}else{if(!this.p){this.notify('⚠️ Pera Wallet not available - using manual entry');const addr=prompt('Enter Algorand wallet:');if(addr&&addr.length===58){this.w=addr;this.saveW();this.b.AMINA=await this.fetchAmina(addr);await this.refSess();this.forceAMINA();this.updWal();this.notify('✅ Wallet connected manually');this.vib([50,100,50]);if($('welcomeScreen').classList.contains('active'))setTimeout(()=>this.enter(),1e3)}else if(addr)this.notify('❌ Invalid address');return}try{const re=await this.p.reconnectSession();if(re&&re.length>0){this.w=re[0];this.saveW();this.b.AMINA=await this.fetchAmina(this.w);await this.refSess();this.forceAMINA();this.updWal();this.notify('🚀 Pera Wallet reconnected!');this.vib([50,100,50]);if($('welcomeScreen').classList.contains('active'))setTimeout(()=>this.enter(),1e3);return}const acc=await this.p.connect();if(acc&&acc.length>0){this.w=acc[0];this.saveW();this.b.AMINA=await this.fetchAmina(this.w);await this.refSess();this.forceAMINA();this.updWal();this.notify('🚀 Pera Wallet connected!');this.vib([50,100,50]);if($('welcomeScreen').classList.contains('active'))setTimeout(()=>this.enter(),1e3)}else this.notify('❌ No accounts found')}catch(e){this.notify(e.type===4001||e.message?.includes('cancelled')?'❌ Connection cancelled':e.message?.includes('rejected')?'❌ Connection rejected':'❌ Connection failed - check Pera Wallet app')}}}
forceHC(){this.c='HC';this.updCur();this.updBets();this.updDisp();this.saveApp()}
forceAMINA(){if(this.w&&this.cc<0.001){this.notify('❌ Need at least 0.001 AMINA to switch. Visit Cashier!');this.forceHC();return!1}if(!this.w){this.forceHC();return!1}this.c='AMINA';this.updCur();this.updBets();this.updDisp();this.saveApp();return!0}
updWal(){const btn=$('walletBtn');btn.innerHTML=this.w?'🔓 '+this.w.slice(0,4)+'...'+this.w.slice(-4):'🔗 Connect Wallet'}
async togCur(){if(!this.w){this.notify('🔗 Connect wallet for AMINA!');this.vib(100);return}if(this.c==='HC'){if(this.forceAMINA())this.notify('🪙 Switched to AMINA mode')}else{this.forceHC();this.notify('🏠 Switched to HC mode')}this.vib(50)}
updBets(){const bets=this.c==='HC'?['1','5','10']:['0.001','0.005','0.01'];['slots','plinko','blackjack','hilo','dice'].forEach(g=>{const sel=$(`${g}Bet`);if(sel){sel.innerHTML='';bets.forEach(b=>{const opt=document.createElement('option');opt.value=opt.textContent=b;sel.appendChild(opt)});sel.value=bets[0]}})}
updDisp(){const bal=this.c==='AMINA'?this.cc:this.b.HC;$('balanceAmount').textContent=this.c==='AMINA'?this.trimZeros(bal.toFixed(8)):bal.toFixed(0);$('currencySymbol').textContent=this.c;this.anim();['slots','plinko','blackjack','hilo','dice'].forEach(g=>{const el=$(`${g}Currency`);if(el)el.textContent=this.c})}
trimZeros(str){return str.replace(/\.?0+$/,'')}
async valBal(){if(this.c==='AMINA'&&this.cc<0.001){this.notify('💰 Please top up your AMINA balance!');this.forceHC();return!1}return!0}
async deduct(amt){if(!await this.valBal())return 0;if(this.c==='AMINA'){if(this.cc<amt){this.notify('❌ Insufficient AMINA credits! Visit Cashier.');this.vib(100);return 0}this.cc-=amt;this.updDisp();const suc=await this.updServ('deduct_credits',amt);if(!suc)this.notify('⏸️ Sync pending...');return 1}else{if(this.b.HC<amt){this.notify('❌ Insufficient HC balance!');this.vib(100);return 0}this.b.HC-=amt;this.saveHC();this.updDisp();return 1}}
async add(amt,src='win'){if(this.c==='AMINA'&&src==='win'){this.cc+=amt;this.updDisp();const suc=await this.updServ('add_credits',amt);if(!suc)this.notify('⏸️ Sync pending...');this.vib([25,50,25])}else{this.b.HC+=amt;this.saveHC();this.updDisp();this.vib([25,50,25])}}
switch(id){this.vib(25);$$('.game-screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');const games={slots:()=>this.initSlots(),plinko:()=>this.initPlinko(),blackjack:()=>this.initBJ(),hilo:()=>this.initHilo(),dice:()=>this.initDice(),cashier:()=>this.initCash()};if(games[id])games[id]()}
notify(msg,type='info'){const div=document.createElement('div');div.textContent=msg;div.style.cssText=`position:fixed;top:20px;right:20px;z-index:1001;background:${type==='error'?'#F44336':'#FFD700'};color:#000;padding:1rem 2rem;border-radius:15px;font-family:JetBrains Mono,monospace;font-weight:700;transform:translateX(100%);transition:transform .3s ease;max-width:300px;word-wrap:break-word;box-shadow:0 8px 25px rgba(0,0,0,0.3)`;document.body.appendChild(div);setTimeout(()=>div.style.transform='translateX(0)',50);setTimeout(()=>{div.style.transform='translateX(100%)';setTimeout(()=>div.remove(),300)},3e3)}
showRes(game,msg,type='info'){const el=$(`${game}Result`);if(el){el.textContent=msg;el.className=`game-result show ${type}`;if(type==='win'&&msg.includes('MEGA')){el.classList.add('mega-win');this.vib([100,50,100,50,100])}else if(type==='win')this.vib([50,25,50]);setTimeout(()=>el.classList.remove('show','mega-win'),4e3)}}
setupGames(){}
setupMusic(){const btn=$('musicToggle');this.m.aud=document.createElement('audio');Object.assign(this.m.aud,{loop:1,volume:.3,src:'https://dn721902.ca.archive.org/0/items/tvtunes_26876/Hot%20Butter%20Popcorn.mp3',crossOrigin:'anonymous'});this.m.on=1;this.m.aud.play().catch(()=>{this.m.on=0;btn.innerHTML='🔇'});btn.onclick=()=>{if(this.m.on){this.m.aud.pause();btn.innerHTML='🔇';this.m.on=0;this.notify('🎵 Music off')}else{this.m.aud.play().catch(()=>this.notify('❌ Music failed to load'));btn.innerHTML='🎵';this.m.on=1;this.notify('🎵 Hot Butter Popcorn!')}}}
createFX(){setInterval(()=>{if(Math.random()<.3)this.createPart()},3e3)}
createPart(){const el=document.createElement('div'),syms=['✨','⭐','🌟','💫'];el.textContent=syms[Math.floor(Math.random()*4)];el.style.cssText=`position:fixed;font-size:${Math.random()*10+15}px;pointer-events:none;z-index:-1;left:${Math.random()*100}%;top:100vh;opacity:${Math.random()*.6+.2};animation:floatUp ${Math.random()*4+6}s linear forwards`;document.body.appendChild(el);setTimeout(()=>el.remove(),1e4)}
initCash(){$('depositBtn').onclick=()=>this.notify('Connect wallet first');$('withdrawBtn').onclick=()=>this.notify('Connect wallet first')}
initSlots(){this.notify('🎰 Slots coming soon!')}
initPlinko(){this.notify('🌌 Plinko coming soon!')}
initBJ(){this.notify('♠️ Blackjack coming soon!')}
initHilo(){this.notify('📈 Hi-Lo coming soon!')}
initDice(){this.notify('🎲 Dice coming soon!')}
}
function $(id){return document.getElementById(id)}
function $$(sel){return document.querySelectorAll(sel)}
function openAminaExplorer(){window.open('https://explorer.perawallet.app/asset/1107424865/','_blank')}
function showDonationModal(){$('donationModal').style.display='flex'}
function closeDonationModal(){$('donationModal').style.display='none'}
function copyDonationAddress(){const input=$('donationWallet');input.select();document.execCommand('copy');alert('Address copied! 🚀');}
let casino;
document.addEventListener('DOMContentLoaded',()=>{casino=new AminaCasino();});
window.casino=casino;
